package com.bank.accountservice.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.util.List;

@Entity
@Table(name = "customers") // تحديد اسم الجدول في قاعدة البيانات
@Data // يقوم Lombok بإنشاء Getters, Setters, toString, equals, hashCode
@NoArgsConstructor // يقوم Lombok بإنشاء مُنشئ بدون وسائط
@AllArgsConstructor // يقوم Lombok بإنشاء مُنشئ بكل الوسائط
public class Customer {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // توليد تلقائي للمفتاح الرئيسي
    private Long id;

    @Column(nullable = false, unique = true)
    private String nationalId; // الرقم الوطني أو رقم الهوية

    @Column(nullable = false)
    private String firstName;

    @Column(nullable = false)
    private String lastName;

    @Column(nullable = false)
    private String email;

    @Column(nullable = false)
    private String phoneNumber;

    // علاقة One-to-Many: العميل يمكن أن يكون لديه عدة حسابات
    // CascadeType.ALL: أي عملية على العميل تؤثر على الحسابات المرتبطة
    // orphanRemoval = true: حذف الحسابات إذا تم فصلها عن العميل
    @OneToMany(mappedBy = "customer", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Account> accounts;

    // Constructors, Getters, Setters will be generated by Lombok's @Data, @NoArgsConstructor, @AllArgsConstructor
}